import React, { useState } from "react";
import { useForm } from "react-hook-form";

// ShowData component to display the list of skills
// This component receives a list of skills as props and renders them in a table
// Each skill is displayed in a separate row with its title
// The table is styled using Bootstrap classes for better appearance
// It uses the map function to iterate over the skills array and create table rows

const ShowData = ({ skills }) => {
    return React.createElement(
        "table", 
        { className: "table table-striped table-bordered mt-3" }, 
        React.createElement(
            "tbody",
            null,
        skills.map((skill, ) =>
            React.createElement("tr", 
                {key: skill.id },
                React.createElement("td", null, skill.title),
            )
        )
    )
    );
};
// Form component to add new skills
// This component uses react-hook-form for form handling
// It includes an input field for the skill title and a submit button
// When the form is submitted, it calls the onAdd function passed as a prop
// to add the new skill to the skills list

const Form = ({ onAdd}) => {
    // useForm hook to manage form state and validation
    // register function is used to register the input field
    // handleSubmit function is used to handle form submission
    // reset function is used to clear the form after submission
    const { register, handleSubmit, reset } = useForm();

    const onSubmit = (data) => {
        const newSkill = {
            id: crypto.randomUUID(),
            title: data.title,
        };
        console.log("new skill added",newSkill);


        onAdd(newSkill);
        reset();
    };
    return React.createElement(
        "form",
        { onSubmit: handleSubmit(onSubmit), className: "mt-3" },
        React.createElement("input",{
            ...register("title", { required: true }),
            className: "form-control mb-2",
            placeholder: "Enter skill title"
        }),
        React.createElement("button",
            { type: "submit", className: "btn btn-primary" },
            "Add Skill"
        )
    );
}
// Skill component that combines Form and ShowData components
// This component maintains the state of the skills list
// It initializes the skills with some predefined values
// It also provides a function to add new skills to the list
// The component renders the Form for adding skills and ShowData for displaying them
const Skill = () => {
    // State to hold the list of skills
    // It uses useState hook to manage the skills array
    // Initial skills are set with unique IDs generated by crypto.randomUUID()
    const [skills, setSkills] = useState([
        {id : crypto.randomUUID(), title: "React"},
        {id : crypto.randomUUID(), title: "JavaScript"},
        {id : crypto.randomUUID(), title: "CSS"},
        {id : crypto.randomUUID(), title: "HTML"},
        {id : crypto.randomUUID(), title: "Node.js"},
        
    ]);
    

// Function to add a new skill to the skills list
// It updates the state by appending the new skill to the existing skills array
// This function is passed down to the Form component as a prop

const addSkill = (skill) => {
    setSkills((prevSkills) => [...prevSkills, skill]);
}
    return React.createElement(
        "div",
        { className: "container mt-5" },
        React.createElement("h2" , null, "Skills App"),
        React.createElement(Form, { onAdd: addSkill }),
        React.createElement(ShowData, { skills: skills })
    );
};

export default Skill;

            